db_name: "jwt_auth"
db_port: "5431"
db_host: "host.docker.internal"
db_user: "postgres"
db_password: "admin123"

jwt_signing_key: "TfpLCZ3VemKCCooNnzhSmgi0FqQ/YQmPsyiirfih+m4="
token_hour_lifespan: 1
